# SwiftLint configuration for TestCaseEvaluator
# Adapted from LeetPaulse app config -- app-specific UI rules removed,
# thresholds relaxed for generated test code and algorithmic solutions.
#
# This project embeds unmodified algorithm solutions from LeetCode into
# generated test harnesses. Many lint rules fire on the solution code which
# we intentionally do not rewrite. Rules disabled below are those triggered
# exclusively or primarily by embedded solution patterns.

included:
  - Tests
  - Sources

excluded:
  - .build
  - "**/.build"
  - DerivedData
  - .xcode_derived_data
  - build
  - Generated
  - "**/*.generated.swift"
  - Scripts

# Disable rules that fire on embedded algorithmic solution code.
# These patterns are inherent to algorithm implementations and cannot
# be fixed without rewriting solution logic.
disabled_rules:
  - for_where                  # Algorithmic loops with conditional bodies
  - statement_position          # Brace style in embedded solutions
  - trailing_semicolon          # Embedded solutions may have semicolons
  - comma                       # Embedded solution spacing
  - colon                       # Embedded solution spacing
  - control_statement           # Embedded solution patterns
  - syntactic_sugar             # Embedded solutions may use Array<T> etc.
  - large_tuple                 # Algorithmic return types + test case tuples
  - implicit_optional_initialization  # Solution patterns
  - empty_parentheses_with_trailing_closure  # Solution patterns
  - vertical_whitespace         # Generated file spacing

# Keep default rules + add high-signal opt-ins
opt_in_rules:
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports
  - closure_spacing
  - redundant_nil_coalescing
  - redundant_type_annotation
  - yoda_condition

# Relaxed for generated test code: force-unwrap/cast are acceptable in test harnesses
force_cast: warning
force_try: warning
force_unwrapping: warning
implicitly_unwrapped_optional: warning

# Naming conventions
type_name:
  min_length: 2
  max_length:
    warning: 60
    error: 80

identifier_name:
  min_length:
    warning: 2
    error: 1
  validates_start_with_lowercase: warning
  allowed_symbols: ["_"]
  excluded:
    - id
    - URL
    - rv
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - n
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - y
    - z
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - J
    - K
    - M
    - N
    - P
    - R
    - S
    - T
    - X
    - Y
    - lo
    - hi
    - dp
    - lp
    - rp
    - st
    # LeetCode API method/class names that cannot be renamed
    - Front
    - Rear
    - PredictTheWinner

# API cleanliness
function_parameter_count:
  warning: 10
  error: 15

# Complexity / size guardrails -- relaxed for generated test files and algorithmic solutions
cyclomatic_complexity:
  warning: 25
  error: 50

function_body_length:
  warning: 200
  error: 400

type_body_length:
  warning: 2000
  error: 6000

file_length:
  warning: 3000
  error: 6000
  ignore_comment_only_lines: true

line_length:
  warning: 200
  error: 2000
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

nesting:
  type_level: 3
  function_level: 5
