# SwiftLint configuration for TestCaseEvaluator
# Adapted from LeetPaulse app config -- app-specific UI rules removed,
# thresholds relaxed for generated test code and algorithmic solutions.

included:
  - Tests
  - Sources

excluded:
  - .build
  - "**/.build"
  - DerivedData
  - .xcode_derived_data
  - build
  - Generated
  - "**/*.generated.swift"
  - Scripts

# Keep default rules + add high-signal opt-ins
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports
  - closure_spacing
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - yoda_condition

# Relaxed for generated test code: force-unwrap/cast are acceptable in test harnesses
force_cast: warning
force_try: warning
force_unwrapping: warning
implicitly_unwrapped_optional: warning

# Naming conventions
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 70

identifier_name:
  min_length:
    warning: 2
    error: 1
  allowed_symbols: ["_"]
  excluded:
    - id
    - URL
    - x
    - y
    - z
    - i
    - j
    - k
    - l
    - m
    - n
    - p
    - q
    - s
    - t
    - lo
    - hi
    - dp

# API cleanliness
function_parameter_count:
  warning: 6
  error: 8

# Complexity / size guardrails -- relaxed for generated test files and algorithmic solutions
cyclomatic_complexity:
  warning: 20
  error: 30

function_body_length:
  warning: 200
  error: 400

type_body_length:
  warning: 500
  error: 1000

file_length:
  warning: 1000
  error: 2000
  ignore_comment_only_lines: true

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

nesting:
  type_level: 2
  function_level: 3
