// swift-tools-version: 6.2
// GENERATED by Scripts/generate_package.py -- do not edit manually
import PackageDescription

let package = Package(
    name: "TestCaseEvaluator",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "LeetCodeHelpers", targets: ["LeetCodeHelpers"]),
        .library(name: "TestResultsBundle", targets: ["TestResultsBundle"]),
    ],
    targets: [
        .target(
            name: "LeetCodeHelpers",
            path: "Sources/LeetCodeHelpers"
        ),
        .target(
            name: "TestResultsBundle",
            path: "test_results",
            sources: ["TestResultsBundle.swift"],
            resources: [
                .process("arrays-hashing.json"),
                .process("heap-priority-queue.json"),
                .process("intervals.json"),
                .process("sliding-window.json"),
                .process("summary.json"),
                .process("tries.json"),
            ]
        ),
        .testTarget(
            name: "ArraysHashing_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/ArraysHashing_EasyTests"
        ),
        .testTarget(
            name: "ArraysHashing_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/ArraysHashing_MediumTests"
        ),
        .testTarget(
            name: "ArraysHashing_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/ArraysHashing_HardTests"
        ),
        .testTarget(
            name: "Backtracking_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Backtracking_EasyTests"
        ),
        .testTarget(
            name: "Backtracking_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Backtracking_MediumTests"
        ),
        .testTarget(
            name: "Backtracking_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Backtracking_HardTests"
        ),
        .testTarget(
            name: "BinarySearch_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/BinarySearch_EasyTests"
        ),
        .testTarget(
            name: "BinarySearch_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/BinarySearch_MediumTests"
        ),
        .testTarget(
            name: "BinarySearch_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/BinarySearch_HardTests"
        ),
        .testTarget(
            name: "BitManipulation_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/BitManipulation_EasyTests"
        ),
        .testTarget(
            name: "BitManipulation_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/BitManipulation_MediumTests"
        ),
        .testTarget(
            name: "BitManipulation_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/BitManipulation_HardTests"
        ),
        .testTarget(
            name: "DynamicProgramming_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/DynamicProgramming_EasyTests"
        ),
        .testTarget(
            name: "DynamicProgramming_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/DynamicProgramming_MediumTests"
        ),
        .testTarget(
            name: "DynamicProgramming_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/DynamicProgramming_HardTests"
        ),
        .testTarget(
            name: "Graphs_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Graphs_EasyTests"
        ),
        .testTarget(
            name: "Graphs_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Graphs_MediumTests"
        ),
        .testTarget(
            name: "Graphs_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Graphs_HardTests"
        ),
        .testTarget(
            name: "Greedy_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Greedy_EasyTests"
        ),
        .testTarget(
            name: "Greedy_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Greedy_MediumTests"
        ),
        .testTarget(
            name: "Greedy_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Greedy_HardTests"
        ),
        .testTarget(
            name: "HeapPriorityQueue_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/HeapPriorityQueue_EasyTests"
        ),
        .testTarget(
            name: "HeapPriorityQueue_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/HeapPriorityQueue_MediumTests"
        ),
        .testTarget(
            name: "HeapPriorityQueue_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/HeapPriorityQueue_HardTests"
        ),
        .testTarget(
            name: "Intervals_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Intervals_MediumTests"
        ),
        .testTarget(
            name: "Intervals_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Intervals_HardTests"
        ),
        .testTarget(
            name: "LinkedList_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/LinkedList_EasyTests"
        ),
        .testTarget(
            name: "LinkedList_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/LinkedList_MediumTests"
        ),
        .testTarget(
            name: "LinkedList_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/LinkedList_HardTests"
        ),
        .testTarget(
            name: "MathGeometry_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/MathGeometry_EasyTests"
        ),
        .testTarget(
            name: "MathGeometry_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/MathGeometry_MediumTests"
        ),
        .testTarget(
            name: "MathGeometry_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/MathGeometry_HardTests"
        ),
        .testTarget(
            name: "Misc_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Misc_EasyTests"
        ),
        .testTarget(
            name: "Misc_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Misc_MediumTests"
        ),
        .testTarget(
            name: "Misc_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Misc_HardTests"
        ),
        .testTarget(
            name: "SlidingWindow_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/SlidingWindow_EasyTests"
        ),
        .testTarget(
            name: "SlidingWindow_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/SlidingWindow_MediumTests"
        ),
        .testTarget(
            name: "SlidingWindow_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/SlidingWindow_HardTests"
        ),
        .testTarget(
            name: "Stack_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Stack_EasyTests"
        ),
        .testTarget(
            name: "Stack_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Stack_MediumTests"
        ),
        .testTarget(
            name: "Stack_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Stack_HardTests"
        ),
        .testTarget(
            name: "Trees_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Trees_EasyTests"
        ),
        .testTarget(
            name: "Trees_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Trees_MediumTests"
        ),
        .testTarget(
            name: "Trees_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Trees_HardTests"
        ),
        .testTarget(
            name: "Tries_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Tries_EasyTests"
        ),
        .testTarget(
            name: "Tries_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Tries_MediumTests"
        ),
        .testTarget(
            name: "Tries_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/Tries_HardTests"
        ),
        .testTarget(
            name: "TwoPointers_EasyTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/TwoPointers_EasyTests"
        ),
        .testTarget(
            name: "TwoPointers_MediumTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/TwoPointers_MediumTests"
        ),
        .testTarget(
            name: "TwoPointers_HardTests",
            dependencies: ["LeetCodeHelpers"],
            path: "Tests/TwoPointers_HardTests"
        ),
    ]
)
