#!/usr/bin/env python3
"""Generate Package.swift from topics.json configuration.

Reads Scripts/topics.json to produce a Package.swift with:
  - LeetCodeHelpers library target
  - TestResultsBundle library target (with only existing JSON resources)
  - Test targets for each {Topic}_{Difficulty}Tests directory that exists on disk
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PACKAGE_DIR = SCRIPT_DIR.parent
TOPICS_FILE = SCRIPT_DIR / "topics.json"
PACKAGE_FILE = PACKAGE_DIR / "Package.swift"


def load_config() -> dict:
    """Load the canonical topics.json configuration."""
    with open(TOPICS_FILE) as f:
        return json.load(f)


def existing_result_files() -> list[str]:
    """Scan test_results/ for existing JSON files to include as SPM resources.

    Only files that actually exist on disk are included -- SPM .process()
    fails at build time for missing files.
    """
    results_dir = PACKAGE_DIR / "test_results"
    if not results_dir.exists():
        return []
    return sorted(f.name for f in results_dir.glob("*.json"))


def generate_package_swift(config: dict) -> str:
    """Build the full Package.swift content string."""
    topics = config["topics"]
    difficulties = config["difficulties"]

    # Build resource lines from existing JSON files
    result_files = existing_result_files()
    resource_lines = []
    for fname in result_files:
        resource_lines.append(f'                .process("{fname}"),')
    resources_block = "\n".join(resource_lines)

    # Build test target entries -- only for directories that exist on disk
    tests_dir = PACKAGE_DIR / "Tests"
    test_target_lines = []
    skipped = []
    for topic in topics:
        for diff in difficulties:
            name = f"{topic}_{diff}Tests"
            target_path = tests_dir / name
            if not target_path.is_dir():
                skipped.append(name)
                continue
            path = f"Tests/{name}"
            test_target_lines.append(
                f'        .testTarget(\n'
                f'            name: "{name}",\n'
                f'            dependencies: ["LeetCodeHelpers"],\n'
                f'            path: "{path}"\n'
                f'        ),'
            )
    if skipped:
        print(f"  Skipped {len(skipped)} missing directories: {', '.join(skipped)}")
    test_targets_block = "\n".join(test_target_lines)

    return (
        '// swift-tools-version: 6.2\n'
        '// GENERATED by Scripts/generate_package.py -- do not edit manually\n'
        'import PackageDescription\n'
        '\n'
        'let package = Package(\n'
        '    name: "TestCaseEvaluator",\n'
        '    platforms: [.macOS(.v14), .iOS(.v17)],\n'
        '    products: [\n'
        '        .library(name: "LeetCodeHelpers", targets: ["LeetCodeHelpers"]),\n'
        '        .library(name: "TestResultsBundle", targets: ["TestResultsBundle"]),\n'
        '    ],\n'
        '    targets: [\n'
        '        .target(\n'
        '            name: "LeetCodeHelpers",\n'
        '            path: "Sources/LeetCodeHelpers"\n'
        '        ),\n'
        '        .target(\n'
        '            name: "TestResultsBundle",\n'
        '            path: "test_results",\n'
        '            sources: ["TestResultsBundle.swift"],\n'
        '            resources: [\n'
        f'{resources_block}\n'
        '            ]\n'
        '        ),\n'
        f'{test_targets_block}\n'
        '    ]\n'
        ')\n'
    )


def main():
    config = load_config()

    topics = config["topics"]
    difficulties = config["difficulties"]
    max_targets = len(topics) * len(difficulties)
    print(f"Generating Package.swift ({len(topics)} topics x {len(difficulties)} difficulties, "
          f"max {max_targets} test targets)")

    content = generate_package_swift(config)
    PACKAGE_FILE.write_text(content)
    print(f"Wrote {PACKAGE_FILE}")

    # Verify: count must match actual directories on disk
    count = content.count(".testTarget(")
    tests_dir = PACKAGE_DIR / "Tests"
    actual_dirs = sum(
        1 for topic in topics for diff in difficulties
        if (tests_dir / f"{topic}_{diff}Tests").is_dir()
    )
    print(f"Test target count: {count} (of {max_targets} possible)")
    assert count == actual_dirs, (
        f"Expected {actual_dirs} test targets (matching directories), got {count}"
    )


if __name__ == "__main__":
    main()
